### ISSUE TITLE
Problem with dock using ADW icon themes

### ISSUE THREAD

**Issue by phayz** [chislon/LegacyLauncher#1]
I find that when I applied the following theme, including its icons, that the dock icons are lower than before, with the bottom of them cut off. I have looked over the configuration options and can't find anything which may fix the problem

https://play.google.com/store/apps/details?id=kov.theme.ics&feature=search_result

Off-topic:
I LOVE Legacy Launcher. Thankyou SO MUCH for releasing it. The one feature I've seen nowhere else is the ability to switch catalogs in the app drawer.

**Comment by chislon** [comment]
I am doing some testing, and it turns out that Legacy Launcher doesn't handle ActionButton background pngs used in theme like ICS theme. I have to trace back to see how I introduced this bug, because it doesn't appear in ADW Free.

**Comment by phayz** [comment]
Wow! Thanks for such a quick response.

There's one other behaviour I see with the default theme and I wonder if I should also raise this as an issue. There's a small "gap" between the default dock background and the bottom of the screen. I'd prefer that there was no gap.

**Comment by chislon** [comment]
Fixed with 0.39.6. Originally I wrote some code to fix display issues of the dock icons on qHD screens with hard-coded icon widths, basically forcing the ImageView for the ActionButton to squares. The code didn't really make sense. Did it properly this time around. 

Edit: 
About having extra space at the bottom. I don't recall seeing a hard coded padding attribute. The code fix I made might fix this issue a tad, since the view dimensions should be properly sized now.
